// Generated by gencpp from file localisation/request_logical_pose.msg
// DO NOT EDIT!


#ifndef LOCALISATION_MESSAGE_REQUEST_LOGICAL_POSE_H
#define LOCALISATION_MESSAGE_REQUEST_LOGICAL_POSE_H

#include <ros/service_traits.h>


#include <localisation/request_logical_poseRequest.h>
#include <localisation/request_logical_poseResponse.h>


namespace localisation
{

struct request_logical_pose
{

typedef request_logical_poseRequest Request;
typedef request_logical_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct request_logical_pose
} // namespace localisation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localisation::request_logical_pose > {
  static const char* value()
  {
    return "c674f42d46687f11495636db257cd612";
  }

  static const char* value(const ::localisation::request_logical_pose&) { return value(); }
};

template<>
struct DataType< ::localisation::request_logical_pose > {
  static const char* value()
  {
    return "localisation/request_logical_pose";
  }

  static const char* value(const ::localisation::request_logical_pose&) { return value(); }
};


// service_traits::MD5Sum< ::localisation::request_logical_poseRequest> should match 
// service_traits::MD5Sum< ::localisation::request_logical_pose > 
template<>
struct MD5Sum< ::localisation::request_logical_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localisation::request_logical_pose >::value();
  }
  static const char* value(const ::localisation::request_logical_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localisation::request_logical_poseRequest> should match 
// service_traits::DataType< ::localisation::request_logical_pose > 
template<>
struct DataType< ::localisation::request_logical_poseRequest>
{
  static const char* value()
  {
    return DataType< ::localisation::request_logical_pose >::value();
  }
  static const char* value(const ::localisation::request_logical_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localisation::request_logical_poseResponse> should match 
// service_traits::MD5Sum< ::localisation::request_logical_pose > 
template<>
struct MD5Sum< ::localisation::request_logical_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localisation::request_logical_pose >::value();
  }
  static const char* value(const ::localisation::request_logical_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localisation::request_logical_poseResponse> should match 
// service_traits::DataType< ::localisation::request_logical_pose > 
template<>
struct DataType< ::localisation::request_logical_poseResponse>
{
  static const char* value()
  {
    return DataType< ::localisation::request_logical_pose >::value();
  }
  static const char* value(const ::localisation::request_logical_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALISATION_MESSAGE_REQUEST_LOGICAL_POSE_H
