// Generated by gencpp from file localisation/request_logical_poseRequest.msg
// DO NOT EDIT!


#ifndef LOCALISATION_MESSAGE_REQUEST_LOGICAL_POSEREQUEST_H
#define LOCALISATION_MESSAGE_REQUEST_LOGICAL_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace localisation
{
template <class ContainerAllocator>
struct request_logical_poseRequest_
{
  typedef request_logical_poseRequest_<ContainerAllocator> Type;

  request_logical_poseRequest_()
    : request_msg(false)  {
    }
  request_logical_poseRequest_(const ContainerAllocator& _alloc)
    : request_msg(false)  {
  (void)_alloc;
    }



   typedef uint8_t _request_msg_type;
  _request_msg_type request_msg;




  typedef boost::shared_ptr< ::localisation::request_logical_poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localisation::request_logical_poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct request_logical_poseRequest_

typedef ::localisation::request_logical_poseRequest_<std::allocator<void> > request_logical_poseRequest;

typedef boost::shared_ptr< ::localisation::request_logical_poseRequest > request_logical_poseRequestPtr;
typedef boost::shared_ptr< ::localisation::request_logical_poseRequest const> request_logical_poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localisation::request_logical_poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localisation::request_logical_poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace localisation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::localisation::request_logical_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localisation::request_logical_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localisation::request_logical_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localisation::request_logical_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localisation::request_logical_poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localisation::request_logical_poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localisation::request_logical_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "120a515e012d96279de9e81c3aa4b0aa";
  }

  static const char* value(const ::localisation::request_logical_poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x120a515e012d9627ULL;
  static const uint64_t static_value2 = 0x9de9e81c3aa4b0aaULL;
};

template<class ContainerAllocator>
struct DataType< ::localisation::request_logical_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localisation/request_logical_poseRequest";
  }

  static const char* value(const ::localisation::request_logical_poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localisation::request_logical_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool request_msg\n\
";
  }

  static const char* value(const ::localisation::request_logical_poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localisation::request_logical_poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct request_logical_poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localisation::request_logical_poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localisation::request_logical_poseRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_msg: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALISATION_MESSAGE_REQUEST_LOGICAL_POSEREQUEST_H
