
# Competitor trial configuration options

arm:
  type: ur10

sensors:


  #logical_camera_bin6:
  #  type: logical_camera
  #  pose:
  #    xyz: [-0.66, -0.52, 1.36]
  #    rpy: ['pi/2', 1.32, 0]

  logical_camera_bin7:
    type: logical_camera
    pose:
      xyz: [-0.66, 0.22, 1.36]
      rpy: ['pi/2', 1.32, 0]

  logical_camera_bin8:
    type: logical_camera
    pose:
      xyz: [-0.66, 1, 1.36]
      rpy: ['pi/2', 1.32, 0]
